apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-mem-demo
spec:
  containers:
  - name: cpu-container
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
 ---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: cpu-mem-demo
spec:
  containers:
  - name: memory-container
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
