apiVersion: v1
kind: ReplicationController
metadata:
  name: rcontroller001
spec:
  replicas: 10
  selector:
    app: web-hello
  template:
    metadata:
      name: web-pod
      labels:
        app: web-hello
    spec:
      containers:
      - name: web-rc-container
        image: murataksunet/k8s-web-helloo
        ports:
        - containerPort: 80
