apiVersion: v1
kind: Pod
metadata:
  name: node-affinitypod
spec:
  containers:
  - name: affinity-c1
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-istanbul
            operator: In
            values:
            - e2e-az1
            - e2e-az2
            - e2e-az3
