apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod
spec:
  containers:
  - name: affinitycontainer
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disksize
            operator: In
            values:
            - large 
            - medium 
