apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-loadblncr-svc
  labels:
    app: apache
spec:
  selector:
    app: apache
  type: LoadBalancer
  ports:
    - nodePort: 31111
      port: 80
      targetPort: 80
