### Namespace YAML
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
### Secret YAML
apiVersion: v1
kind: Secret
metadata:
  name: mysql-prod-secret
  namespace: production
type: Opaque
stringData:
  MYSQL_DATABASE: test-db
  MYSQL_USER: myadmin
  MYSQL_PASSWORD: onetwothree!
  MYSQL_ROOT_PASSWORD: onetwothree!
---
### PersistentVolume YAML
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
  namespace: production
  labels:
    tier: production
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mydata"
---
### PersistentVolumeClaim YAML
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-prod-claim
  namespace: production
  labels:
    tier: production
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
### Mysql-Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: production
  labels:
    tier: production
    app: mysql
spec:
  selector:
    matchLabels:
      tier: production
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: production
        app: mysql
    spec:
      containers:
      - name: mysql-prod
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-prod-secret
              key: MYSQL_DATABASE
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"      
        ports:
          - containerPort: 3306
            name: mysql-prod-port
        volumeMounts:
          - name: mysql-prod-pv
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-prod-pv
          persistentVolumeClaim:
            claimName: mysql-prod-claim
---
### Mysql-Service YAML
apiVersion: v1
kind: Service
metadata:
  name: mysql-prod-svc
  namespace: production
  labels:
    tier: production
spec:
  selector:
    tier: production
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
### Phpmyadmin-Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: production
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-prod-svc
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-prod-secret
                  key: MYSQL_ROOT_PASSWORD
---
### Phpmyadmin-Service YAML
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
