apiVersion: v1
kind: Secret
metadata:
  name: postsql-secret
type: Opaque
stringData:
  username: admin
  password: t0p-Secret123!
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
       app: drupal
       tier: postgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:latest
          name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postsql-secret
                  key: username
            - name: POSTGRES_DB
              value: drupal_production
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postsql-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: drupal
spec:
  ports:
    - port: 5432
  selector:
    app: drupal
    tier: postgreSQL
