apiVersion: v1
kind: Pod
metadata:
  name: liveness-command-exec
spec:
  containers:
  - name: liveness-command-exec
    image: nginx
    ports:
        - containerPort: 80
    livenessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 2
      periodSeconds: 2
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-http
spec: 
  containers: 
  - name: liveness-http
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      httpGet: 
        path: /index.html
        port: 80
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2 #Default 10 <
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-tcpsocket
spec: 
  containers: 
  - name: liveness-tcpsocket
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      tcpSocket:
        port: 80
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2 #Default 10 
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3
