apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres-cntr
    image: postgres:latest
    env:
    - name: POSTGRES_USER
      value: postgresadmin
    - name: POSTGRES_DB
      value: postgresdb
    - name: POSTGRES_PASSWORD
      value: onetwothree123
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-volume
      mountPath: "/var/lib/postgresql/data"
  volumes:
  - name: postgres-volume
    persistentVolumeClaim:
      claimName: postgres-claim
