apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-pv
   labels:
     app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
   - nfsvers=3
  nfs:
    server: 192.168.99.124
    path: /nfs
