apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvmysql
   labels:
     app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
   - hard
   - nfsvers=3
  nfs:
    path: /c/data
    server: 192.168.99.1
