apiVersion: v1
kind: PersistentVolume
metadata:
   name: postgres-pv
   labels:
     app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
   - nfsvers=3
  nfs:
    server: 192.168.99.124
    path: /nfs
