apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /tmp/storage
