apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-emtdir
spec:
  containers:
  - name: c1
    image: busybox
    command:
      - "sleep"
      - "5000"
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - name: c2
    image: alpine
    command:
      - "sleep"
      - "5000"
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}
