apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: nginx
spec:
  replicas: 10
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: web-deploy-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: web-deploy-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
