apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  labels:
    app: k8s-web
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web
  template:
    metadata:
      labels:
        app: k8s-web
    spec:
      containers:
      - name: k8s-web-container
        image: murataksunet/k8s-basic
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
