apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: web
spec:
  replicas: 10
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 2
     maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: murataksunet/k8s-deploy:v1
        name: web-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
