apiVersion: v1
kind: Pod
metadata:
  name: production-backend
  labels:
    env: production
    tier: backend
spec:
  containers:
  - name: application-container
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: production-frontend
  labels:
    env: production
    tier: frontend
spec:
  containers:
  - name: application-container
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-frontend
  labels:
    env: demo
    tier: frontend
spec:
  containers:
  - name: application-container
    image: nginx
