apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rcontroller
spec:
  replicas: 3
  selector:
    app: web-rc-demo
  template:
    metadata:
      name: web-rc-pod
      labels:
        app: web-rc-demo
    spec:
      containers:
      - name: web-rc-container
        image: murataksunet/k8s-replicationcontroller
        ports:
        - containerPort: 80
