apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: secretcontainer
    image: redis
    env:
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_server
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_username
      - name: DB_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_password
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: secretpodvolume
spec:
  containers:
  - name: secretcontainer
    image: redis
    volumeMounts:
    - name: secret-vol
      mountPath: /secret
  volumes:
  - name: secret-vol
    secret:
      secretName: mysecret
---
apiVersion: v1
kind: Pod
metadata:
  name: secretpodallenv
spec:
  containers:
  - name: secretcontainer
    image: redis
    envFrom:
    - secretRef:
        name: mysecret
