apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  db_name: postgresdb
  db_username: postgresadmin
  db_password: onetwothree123
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-postress-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres-container
    image: postgres:latest
    env:
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_name
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: db_password
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-volume
      mountPath: "/var/lib/postgresql/data"
  volumes:
  - name: postgres-volume
    hostPath:
      path: "/storage"
