apiVersion: v1
kind: Pod
metadata:
  name: pod-ram-cpu-limit
spec:
  containers:
  - name: hardware-limit-pod
    image: nginx
    resources:
      limits:
        memory: "128M"
        cpu: "0.5"
      requests:
        memory: "10M"
        cpu: "0.1"
